# Generated by Django 2.2.28 on 2022-11-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addressrahuhrikte'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressrahuhrikte',
            name='ca',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
